AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  App:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda-mackerel2route53
      Runtime: go1.x
      Timeout: 15
      MemorySize: 128
      CodeUri: build/
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /
            Method: post