AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  App:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: mackerel-webhook-gateway
      Handler: mackerel-webhook-gateway
      Runtime: go1.x
      Timeout: 15
      MemorySize: 128
      CodeUri: ../../build/
      Environment:
        Variables:
          MACKEREL2ROUTE53_ZONE_ID: !ImportValue 'mackerel2route53-zones:ZoneID'
          MACKEREL2ROUTE53_ZONE_NAME: !ImportValue 'mackerel2route53-zones:ZoneName'
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /
            Method: post